CREATE TABLE IF NOT EXISTS gallery_images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  image_data MEDIUMBLOB NOT NULL,
  image_mime_type VARCHAR(100) NOT NULL DEFAULT 'image/webp',
  category VARCHAR(100) NOT NULL DEFAULT 'General',
  caption TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
